<a href="https://colab.research.google.com/github/anubhavgupta1/Deep-Learning-Using-TensorFlow/blob/master/3_Tensor_Flow_Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.10.0

     |████████████████████████████████| 58.4MB 76kB/s 
     |████████████████████████████████| 12.2MB 20.2MB/s 
     |████████████████████████████████| 573kB 43.6MB/s 
     |████████████████████████████████| 3.3MB 43.6MB/s 
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: umap-learn 0.4.6 has requirement numpy>=1.17, but you'll have numpy 1.14.5 which is incompatible.
ERROR: tifffile 2020.9.3 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
ERROR: spacy 2.2.4 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: seaborn 0.11.0 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: pandas 1.1.4 has requirement num

In [2]:
import numpy as np
import tensorflow as tf
import os
import matplotlib
import matplotlib.pyplot as plt
from datetime import datetime
from __future__ import division, print_function, unicode_literals
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler




/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [3]:
x = 1
y = 2

In [4]:
f = x*x*y + y + 2
f

6

In [5]:
f

6

In [6]:
x = 3

In [7]:
f = x*x*y + y + 2
f

22

In [8]:
def differentiate(f, x):
    dx = 0.00001
    return (f(x+dx) - f(x))/dx

In [9]:
def sq(x):
    return x*x

def cube(x):
    return x*x*x

In [10]:
differentiate(sq, 5)

10.000009999444615

In [11]:
differentiate(cube, 5)

75.00014999664018

In [12]:
def fn(x,y):
  return x*x*y + y + 2

In [13]:
X = np.array([[1, 5/3], [1, 1/9]])
y = np.array([12/3, 21/9])
np.linalg.inv(X.T.dot(X)) .dot(X.T).dot(y)

array([2.21428571, 1.07142857])

###**Setup**

In [14]:
# Check the tensorflow version
print(tf.__version__)

1.10.0


In [15]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# To plot pretty figures
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "tensorflow"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

###**Creating and running a graph**

In [16]:
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = "tf_logs"
logdir = "{}/run-{}/".format(root_logdir, now)

In [17]:
reset_graph()
x = tf.Variable(3, name="x")
y = tf.Variable(4, name="y")
f = x*x*y + y + 2
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [18]:
g = tf.get_default_graph()

In [19]:
file_writer.close()

In [20]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)
sess.close()

42


In [21]:
# Better way
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = sess.run(f)
    print(result)
result

42


42

In [22]:
# Better way
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()
    print(result)
result

42


42

In [23]:
# Another better way

init = tf.global_variables_initializer() # prepare an init node

with tf.Session() as sess:
    init.run() # actually initialize all the variables
    result = f.eval()

result

42

In [24]:
# Another better way

init = tf.global_variables_initializer() # prepare an init node

with tf.Session() as sess:
    init.run() # actually initialize all the variables
    print(f.eval())
    print(sess.run(f))

42
42


###**Managing graphs**

In [25]:
reset_graph()
x1 = tf.Variable(1)

In [26]:
tf.get_default_graph()

In [27]:
x1.graph is tf.get_default_graph()
print(tf.get_default_graph())

In [28]:
graph1 = tf.Graph()

with graph1.as_default():
    x2 = tf.Variable(2)

print(x2.graph is graph1)
print(x2.graph is tf.get_default_graph())

True
False


In [29]:
# To reset the default group
reset_graph()

###**Lifecycle of a Node Value**

In [30]:
graph1.get_collection('variables')

[<tf.Variable 'Variable:0' shape=() dtype=int32_ref>]

In [31]:
g = tf.get_default_graph()
g.get_operations()

[]

In [32]:
npa = np.array([1,2,3])

In [33]:
init = tf.global_variables_initializer() # prepare an init node

with tf.Session() as s:
    init.run()
    #print(g.get_operation_by_name('s'))

In [34]:
w = tf.constant(3)
x = w + 2
y = x + 5
z = x * 3

with tf.Session() as sess:
    print(y.eval())  # 10
    print(z.eval())  # 15

10
15


In [35]:
zz = tf.square(y+z)
with tf.Session() as s:
    zz_v, z_v, y_v = s.run([zz, z, y])
print(zz_v)

625


In [36]:
# Run previous code efficiently

with tf.Session() as sess:
    y_val, z_val = sess.run([y, z])
    print(y_val)  # 10
    print(z_val)  # 15

10
15


###**Linear Regression Using numpy**

In [37]:
X = np.array([[1,5/3],[1, 1/9]])
y = np.array([[12/3],[21/9]])

# (XT.X)-1  .XT   .y
xt = X.T
xtx = xt.dot(X)
ixtx =  np.linalg.inv(xtx)

theta_best = ixtx.dot(xt).dot(y)
theta_best = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
theta_best

array([[2.21428571],
       [1.07142857]])

###**Using the Normal Equation**

In [38]:
reset_graph()

In [39]:
np.array([1, 2, 3]) - np.array([3, 2, 1])

array([-2,  0,  2])

In [40]:
housing = fetch_california_housing()
m, n = housing.data.shape

In [41]:
housing.data[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [42]:
housing.target[0]

4.526

In [43]:
mydata = np.array([[2, 3], [5,6]])

In [44]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
mydata

array([[2, 3],
       [5, 6]])

In [46]:
np.c_[np.ones((2, 1)), mydata]

array([[1., 2., 3.],
       [1., 5., 6.]])

In [47]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [48]:
v = np.array([1,2,3,4, 6, 7])
v

array([1, 2, 3, 4, 6, 7])

In [49]:
v1 = v.reshape((-1, 2))
v1

array([[1, 2],
       [3, 4],
       [6, 7]])

In [50]:
v1.T

array([[1, 3, 6],
       [2, 4, 7]])

In [51]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

In [52]:
# Calculate theta using normal equation in TensorFlow
# We will use housing dataset of end-to-end project

reset_graph()

housing = fetch_california_housing()
m, n = housing.data.shape

housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

# (XT.X)-1  .XT   .y

XT = tf.transpose(X)
theta = tf.matmul(
    tf.matmul(
        tf.matrix_inverse(
            tf.matmul(
                XT, 
                X)), 
        XT), 
    y)

# theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul( tf.transpose(X), X)),  
#                             tf.transpose(X)), y)

with tf.Session() as sess:
    theta_value = theta.eval()
theta_value

array([[-3.7185181e+01],
       [ 4.3633747e-01],
       [ 9.3952334e-03],
       [-1.0711310e-01],
       [ 6.4479220e-01],
       [-4.0338000e-06],
       [-3.7813708e-03],
       [-4.2348403e-01],
       [-4.3721911e-01]], dtype=float32)

In [53]:
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [54]:
housing.target.reshape(-1, 1)


array([[4.526],
       [3.585],
       [3.521],
       ...,
       [0.923],
       [0.847],
       [0.894]])

In [55]:
# Compare it with pure NumPy
# Calculate theta using normal equation in NumPy

X = housing_data_plus_bias
y = housing.target.reshape(-1, 1)
theta_numpy = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

print(theta_numpy)

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


In [56]:
# Compare it with pure NumPy
# Calculate theta using Scikit-Learn

lin_reg = LinearRegression()
lin_reg.fit(housing.data, housing.target.reshape(-1, 1))

print(np.r_[lin_reg.intercept_.reshape(-1, 1), lin_reg.coef_.T])

[[-3.69419202e+01]
 [ 4.36693293e-01]
 [ 9.43577803e-03]
 [-1.07322041e-01]
 [ 6.45065694e-01]
 [-3.97638942e-06]
 [-3.78654265e-03]
 [-4.21314378e-01]
 [-4.34513755e-01]]


###**Using Batch Gradient Descent**

In [57]:
# Gradient Descent requires scaling the feature vectors first
# We could do this using TF, but let's just use Scikit-Learn for now.

scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]

print(scaled_housing_data_plus_bias.mean(axis=0))
print(scaled_housing_data_plus_bias.mean(axis=1))
print(scaled_housing_data_plus_bias.mean())
print(scaled_housing_data_plus_bias.shape)

[ 1.00000000e+00  6.60969987e-17  5.50808322e-18  6.60969987e-17
 -1.06030602e-16 -1.10161664e-17  3.44255201e-18 -1.07958431e-15
 -8.52651283e-15]
[ 0.38915536  0.36424355  0.5116157  ... -0.06612179 -0.06360587
  0.01359031]
0.11111111111111005
(20640, 9)


In [58]:
scaled_housing_data_plus_bias.shape

(20640, 9)

In [59]:
n

8

In [60]:
# Step 2- Manually computing the gradient
# The Code is self-explanatory, except for a few new elements

'''

1. random_uniform() - The random_uniform() function creates a node in the graph that will generate a tensor containing
random values, given its shape and value range, much like NumPy’s rand() function.

2. assign() - The assign() function creates a node that will assign a new value to a variable. In this case, it
implements the Batch Gradient Descent step θ(next step) = θ – η∇θMSE(θ).

3. The main loop executes the training step over and over again (n_epochs times), and every 100 iterations it prints 
out the current Mean Squared Error (mse). We can see the MSE go down at every iteration

'''

reset_graph()

n_epochs = 10000
learning_rate = .1

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
m, n = housing.data.shape
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")

y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 10 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        x = sess.run(training_op)
    best_theta = theta.eval()
print(best_theta)
print(x)

Epoch 0 MSE = 9.161543
Epoch 10 MSE = 0.66590255
Epoch 20 MSE = 0.5652157
Epoch 30 MSE = 0.5554022
Epoch 40 MSE = 0.5486719
Epoch 50 MSE = 0.54350525
Epoch 60 MSE = 0.53950936
Epoch 70 MSE = 0.5364025
Epoch 80 MSE = 0.53397423
Epoch 90 MSE = 0.53206617
Epoch 100 MSE = 0.5305595
Epoch 110 MSE = 0.5293639
Epoch 120 MSE = 0.528411
Epoch 130 MSE = 0.52764815
Epoch 140 MSE = 0.52703446
Epoch 150 MSE = 0.52653974
Epoch 160 MSE = 0.5261395
Epoch 170 MSE = 0.5258139
Epoch 180 MSE = 0.52554905
Epoch 190 MSE = 0.5253327
Epoch 200 MSE = 0.52515554
Epoch 210 MSE = 0.52501005
Epoch 220 MSE = 0.5248907
Epoch 230 MSE = 0.5247927
Epoch 240 MSE = 0.5247114
Epoch 250 MSE = 0.5246444
Epoch 260 MSE = 0.52458924
Epoch 270 MSE = 0.5245437
Epoch 280 MSE = 0.52450603
Epoch 290 MSE = 0.5244742
Epoch 300 MSE = 0.5244485
Epoch 310 MSE = 0.5244268
Epoch 320 MSE = 0.52440894
Epoch 330 MSE = 0.5243941
Epoch 340 MSE = 0.52438176
Epoch 350 MSE = 0.52437174
Epoch 360 MSE = 0.52436316
Epoch 370 MSE = 0.52435607
Epoch 3